### ISSUE TITLE
Test - Unhandled exception

### ISSUE THREAD

**Issue by geramg** [igmtz/NCTaskManager#1]
```
`Circle invalidCircle = new Circle(0);

public Circle(int radius) throws IllegalArgumentException{
        if (radius <= 0){
            throw new IllegalArgumentException("The radius must be positive and greater than zero");
        }
        this.radius = radius;
    }`
```

If we don't handle an exception with try/catch block out application will fail on runtime.

**Comment by igmtz** [comment]
try {
            if (radius <= 0){
                throw new IllegalArgumentException("The radius must be positive and greater than zero");
            }
            this.radius = radius;
        } catch (IllegalArgumentException e){
            System.out.println("The radius must be positive and greater than zero");
        }
  

The IllegalArgumentException was handled with a try/catch block in order to improve the runtime execution. Thank you!
